highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


url: http://tanvi-surana.github.io/
baseurl: http://tanvisurana.github.io/
# url: ""
# baseurl: ""
title: Tanvi Surana
author: Tanvi Surana
description: "testing"
avatar: profile12.jpg
email: tanvisurana20@gmail.com
github: tanvi-surana # username
twitter: tan_surana
linkedin: tanvisurana
youtube: tanvisurana20
# needed for travis-ci build
exclude: [vendor]
